"use strict";
// ======================= UN MINIJUEGO POR CAPÍTULO =======================
// [código, posición (índice, o 'after:tipo@lugar' / 'before:tipo@lugar'), juego, lugar, título, opciones, diálogo al ganar]
// Sin lugar (null) el minijuego arranca solo al llegar a ese paso.
const MINIGAME_TABLE=[
  ['1x01','after:talk@desert','mash','desert','Sujeta la puerta de la autocaravana',{time:7},[['N','El gas hace su efecto. Dentro, silencio.']]],
  ['1x02',4,'scrub','jesse','Limpia el ácido del baño de Jesse',{spots:16,time:22}],
  ['1x03',1,'timing','jesse','Krazy-8 esconde un trozo de plato: reacciona',{hits:4,speed:1.6},[['W','Te falta un trozo del plato, Domingo.']]],
  ['1x04',3,'wires',null,'Cortocircuita la batería del BMW con el limpiaparabrisas',{n:4,time:18}],
  ['1x05',2,'sequence','jesse','Enséñale a Jesse el procedimiento correcto',{len:3,rounds:3},[['J','Vale, vale... lo pillo. Más o menos.']]],
  ['1x06',3,'timing','tuco','Lanza el fulminato en el momento justo',{hits:3,speed:1.8,zone:0.12}],
  ['1x07','after:cine','stealth','almacen','Entra en el almacén sin que te vea el vigilante',{guards:3,items:2}],
  ['2x01',1,'count','home','Calcula lo que necesita tu familia: 737.000 $',{rounds:3,unit:1000},[['W','Setecientos treinta y siete mil. Ni un dólar menos.']]],
  ['2x02',1,'timing','hector','Mete la ricina en el burrito sin que Héctor lo vea',{hits:3,speed:1.5}],
  ['2x03','after:ride','balance','hospital','Mantén la calma delante de los médicos',{time:9,drift:0.7}],
  ['2x04',2,'count','jesse','Ayuda a Jesse a reunir el dinero de la fianza',{rounds:2}],
  ['2x05',1,'sequence','jesse','Organiza las rutas de los camellos',{len:4,rounds:2}],
  ['2x06',0,'stealth','spooge','Entra en la casa de Spooge',{guards:2,items:1,speed:0.4}],
  ['2x07',2,'balance','dea','Hank: que no se note el temblor',{time:8,drift:0.9}],
  ['2x08',1,'mash','saul','Mete a Saul en el coche',{time:6}],
  ['2x09',2,'wires','desert','Fabrica una batería casera',{n:5,time:24},[['J','¡¿Con monedas y esponjas?! Está usted loco, señor White.']]],
  ['2x10',1,'mash','hospital','Golpea el dispensador de toallas',{time:5,decay:0.12}],
  ['2x11',3,'count','pollos','Cuenta el pago de Gus',{rounds:3,unit:100}],
  ['2x12',0,'count','jane','Prepara los 480.000 $ de Jesse',{rounds:2,unit:1000}],
  ['2x13',0,'stealth','jane','Entra sin hacer ruido en el apartamento',{guards:2,items:0,speed:0.35}],
  ['3x01',0,'mash','home','Apaga el dinero que arde en la barbacoa',{time:6}],
  ['3x02',1,'balance',null,'Conduce sin perder los nervios',{time:10}],
  ['3x03',1,'stealth','home','Vuelve a entrar en casa a escondidas',{guards:2,items:1}],
  ['3x04',1,'timing','desert','Corrige la mezcla de Jesse',{hits:4}],
  ['3x05',2,'sequence','lavanderia','Memoriza el protocolo del superlaboratorio',{len:4,rounds:3}],
  ['3x06',3,'mash','tuco','Activa la prensa del desguace',{time:7}],
  ['3x07',1,'aim','super','¡Los Primos! Dispara',{need:8,life:1.4,miss:4}],
  ['3x08',1,'balance','hospital','Mantén la compostura delante de Gus',{time:8,zone:0.2}],
  ['3x09',2,'count',null,'Cuenta tu parte',{rounds:2,unit:1000}],
  ['3x10',0,'aim','lavanderia','Caza la mosca',{need:3,fly:true}],
  ['3x11',1,'count','carwash','Cuadra las cuentas del lavadero',{rounds:3}],
  ['3x12',2,'timing','spooge','Acelera en el momento justo',{hits:2,speed:2,zone:0.12}],
  ['3x13',2,'stealth','gale','Llega a la puerta de Gale antes que Mike',{guards:2,items:0,speed:0.6}],
  ['4x01',1,'balance','lavanderia','Aguanta la mirada de Gus',{time:8,zone:0.2,drift:0.8}],
  ['4x02',1,'timing','pawn','Practica a desenfundar',{hits:4,speed:2}],
  ['4x03',0,'stealth','hank','Marie roba en una casa en venta',{guards:2,items:2}],
  ['4x04',1,'sequence','home','Ensaya la historia del blackjack con Skyler',{len:4,rounds:3}],
  ['4x05',1,'aim','motel','¡Emboscada en la recogida!',{need:10,life:1.3}],
  ['4x06',1,'timing','home','Dile a Skyler quién es el peligro',{hits:3}],
  ['4x07',1,'aim','jesse','Jesse juega a "Rage" para no pensar',{need:14,life:1.1,miss:5}],
  ['4x08',1,'sequence','residencia','Héctor deletrea con la campanilla',{len:3,rounds:3}],
  ['4x09',0,'stealth','pollos','Coloca el localizador en el coche de Gus',{guards:3,items:1}],
  ['4x10',1,'balance','lavanderia','Cocina delante de los químicos del cártel',{time:10,zone:0.22}],
  ['4x11',2,'scrub','home','Busca el dinero bajo la casa',{spots:18,time:20,color:'rgba(90,70,50,'}],
  ['4x12',2,'wires','pollos','Monta la bomba',{n:5,time:22}],
  ['4x13',1,'timing','residencia','Héctor: toca la campanilla en el momento justo',{hits:3,speed:1.8,zone:0.1}],
  ['5x01',1,'wires','tuco','Monta el electroimán',{n:4,time:18}],
  ['5x02',1,'count','saul','Reparte la paga de riesgo de los hombres de Mike',{rounds:3,unit:100}],
  ['5x03',1,'stealth','vamonos','Monta el laboratorio sin que te vean los vecinos',{guards:2,items:3}],
  ['5x04',2,'mash','home','Saca a Skyler de la piscina',{time:6}],
  ['5x05',2,'balance','tren','Bombea la metilamina sin que se note en el depósito',{time:12,zone:0.2}],
  ['5x06',1,'mash','saul','Quema la brida para liberarte',{time:8,decay:0.15}],
  ['5x07',1,'balance','desert','Aguanta la mirada de Declan',{time:8}],
  ['5x08',3,'count','home','Intenta contar el dinero del trastero',{rounds:3,unit:10000},[['S','¿Cuánto es suficiente, Walt?']]],
  ['5x09',1,'scrub','home','Busca el localizador en tu coche',{spots:12,time:16,color:'rgba(60,60,60,'}],
  ['5x10',1,'mash','tohajiilee','Cava el agujero para los barriles',{time:9,decay:0.14}],
  ['5x11',1,'sequence','home','Graba la confesión falsa sin equivocarte',{len:5,rounds:2}],
  ['5x12',2,'stealth','jane','Jesse sigue a Walter por la plaza',{guards:3,items:0}],
  ['5x13',1,'balance',null,'Conduce hasta el desierto sin estrellarte',{time:11,drift:0.8}],
  ['5x14',2,'balance','home','Al teléfono: mantén la farsa para salvar a Skyler',{time:10,zone:0.18}],
  ['5x15',1,'mash',null,'Arrastra el barril por la nieve',{time:9,decay:0.16}],
  ['5x16',2,'wires','jack','Monta la ametralladora en el maletero',{n:6,time:26}],
];
for(const [code,pos,game,at,title,opts,lines] of MINIGAME_TABLE){
  const M=MISSIONS.find(m=>m.code===code); if(!M) continue;
  // pos: número de paso, o 'after:tipo@lugar' / 'before:tipo@lugar' (se ancla al paso de la historia, no a su número)
  let i=pos; if(typeof pos==='string'){ const [mode,sel]=pos.split(':'), [ty,lo]=sel.split('@');
    const k=M.steps.findIndex(s=>s.type===ty&&(!lo||s.at===lo)); i=k<0?M.steps.length:(mode==='after'?k+1:k); }
  M.steps.splice(Math.min(i,M.steps.length),0,{type:'game',game,at:at||undefined,obj:title,title,opts,lines:lines||[]});
}
